#!/bin/bash
SHELL_VER="--- Aurora-Shell v5.5.5 installer---"
# FIX: Sentinel Auth Visuals + Separator + CPU/Disk Telemetry

# --- PATH CONFIGURATION ---
OLD_SHELL="$HOME/.aurora-shell_files"
DATA_DIR="$HOME/.aurora-shell_files"
THEME_FILE="$DATA_DIR/aurora-shell_theme"
CONFIG_FILE="$DATA_DIR/aurora-shell_settings"
REPO_BASE="https://raw.githubusercontent.com/YashB-byte/aurora-shell"
GIT_CLONE="https://github.com/YashB-byte/aurora-shell.git"
VER="5.5.5"

echo -e "removing old version" | lolcat
rm -rf "$OLD_SHELL"

echo -e "Making "$DATA_DIR" " | lolcat
mkdir -p "$DATA_DIR"
[ -f "$THEME_FILE" ] && rm "$THEME_FILE"

echo "$SHELL_VER" | lolcat

# -- HELPER: SAFE LOLCAT --
safe_lolcat() {
    if command -v lolcat &> /dev/null; then command lolcat; else cat; fi
}

# --- SYNC ENVIRONMENT ---
sync_env() {
    echo -ne "\033[1;33m🛠️  Syncing Environment... \033[0m"
    if ! command -v brew >/dev/null 2>&1; then
        mkdir -p "$HOME/.brew"
        curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C "$HOME/.brew"
        export PATH="$HOME/.brew/bin:$PATH"
    fi
    brew install figlet lolcat pygments 2>/dev/null
    echo -e "\033[1;32mREADY\033[0m"
}

# --- DEV TOOLS BOOTSTRAP (BASH 3.2 SAFE) ---
dev_tools_bootstrap() {
    echo -e "\n\033[1;36m--- DEV TOOLS SETUP (HYBRID MODE) ---\033[0m"

    tools=(
        "Git:git"
        "GitHub_CLI:gh"
        "NodeJS:node"
        "Python3:python@3.14"
        "Java:openjdk"
        "Go:go"
        "Rust:rust"
        "Docker:docker-desktop"
        "AWS_CLI:awscli"
        "Azure_CLI:azure-cli"
    )

    for entry in "${tools[@]}"; do
        name="${entry%%:*}"
        formula="${entry##*:}"

        printf "Install %s? (y/n): " "$name"
        read ans
        if [ "$ans" = "y" ]; then
            case "$name" in
                "Docker")
                    if command -v sudo >/dev/null 2>&1; then
                        brew install --cask docker-desktop
                    else
                        echo "Skipping Docker: sudo not available for this user."
                    fi
                    ;;
                *)
                    brew install "$formula"
                    ;;
            esac
        fi
    done
}

# --- CONFIG WIZARD ---
run_wizard() {
    echo -e "\n\033[1;32m--- AURORA CONFIGURATION WIZARD ---\033[0m"
    [ -f "$CONFIG_FILE" ] && source "$CONFIG_FILE"
    
    read -s -p "🔐 Set Terminal PIN (Enter for none): " NEW_PW < /dev/tty; echo ""
    echo "🎨 1) Mega-Block 2) Custom Slant"
    read -p "Selection: " choice < /dev/tty
    if [ "$choice" == "2" ]; then 
        HDR_MODE="CUSTOM"; read -p "✍️ Header Name: " HDR_VAL < /dev/tty
    else 
        HDR_MODE="BLOCK"; HDR_VAL="Aurora-Shell"
    fi

    printf "🎂 Birthday (MMDD): "
    read BDAY
    printf "🆔 Prompt ID: "
    read P_ID

    cat << EOF > "$CONFIG_FILE"
AURORA_VER="$VER"
AURORA_PW="${NEW_PW:-$AURORA_PW}"
AURORA_HDR_MODE="$HDR_MODE"
AURORA_HDR_VAL="$HDR_VAL"
AURORA_USER_BDAY="${BDAY:-$AURORA_USER_BDAY}"
AURORA_ID="${P_ID:-$AURORA_ID}"
EOF
}

# --- THEME ENGINE ---
generate_theme() {
cat << 'EOF' > "$THEME_FILE"
#!/bin/zsh
# Generated by Aurora-Shell Installer
source "$HOME/.aurora-shell_files/aurora-shell_settings"

# -- HELPER: SAFE LOLCAT --
safe_lolcat() {
    if command -v lolcat &> /dev/null; then command lolcat; else cat; fi
}

# -- XCODE INSTALLER (macOS) --
install_xcode_if_needed() {
    # Only attempt on macOS
    if [[ "$(uname)" != "Darwin" ]]; then
        return
    fi

    # If Xcode.app exists, do nothing
    if [ -d "/Applications/Xcode.app" ] || [ -d "$HOME/Applications/Xcode.app" ]; then
        echo "✔ Xcode found."
        return
    fi

    echo "⚠ Xcode not found — attempting installation...(press Ctrl+C to cancel)"

    # Ensure Homebrew exists
    if ! command -v brew &> /dev/null; then
        echo "⚠ Homebrew missing — installing Homebrew...(press Ctrl+C to cancel)"
        mkdir -p "$HOME/.brew"
        curl -L https://github.com/Homebrew/brew/tarball/master \
            | tar xz --strip 1 -C "$HOME/.brew"
        export PATH="$HOME/.brew/bin:$PATH"
    fi

    # Try installing full Xcode via cask (requires App Store download)
    if brew info --cask xcode >/dev/null 2>&1; then
        echo "⬇ Installing Xcode via App store..."
        open https://apps.apple.com/us/app/xcode/id497799835?mt=12 || true
    fi

    # Fallback: ensure Command Line Tools are installed
    if ! xcode-select -p >/dev/null 2>&1; then
        echo "⬇ Installing Xcode Command Line Tools..."
        xcode-select --install || true
    fi
}

install_xcode_if_needed

authenticate_user() {
    local target_pw="${1:-$AURORA_PW}"
    [[ -z "$target_pw" ]] && return
    clear
    echo "           .---.
          /     \\
         | (00)  |  SYSTEM ENCRYPTED
          \\  ^  /
           '---'
     ╔════════════════════════════════════════╗
     ║     AURORA-SHELL SECURITY TERMINAL     ║
     ╚════════════════════════════════════════╝" | safe_lolcat
    while true; do
        echo -ne "[AUTH] Key: " | safe_lolcat
        if ! read -s in_pw; then
            echo ""
            echo "DENIED"
            continue
        fi
        echo ""

        if [[ "$in_pw" == "$target_pw" ]]; then
            if [[ ! -o interactive ]]; then
                trap INT
                trap TSTP
                trap QUIT
            fi
            clear
            break
        else
            echo "DENIED"
        fi
    done
}

Show-Aurora() {
    source "$HOME/.aurora-shell_files/aurora-shell_settings"
    local cols=$(tput cols)
    local content=""

    if [[ "$AURORA_HDR_MODE" == "BLOCK" ]]; then
        content="
 █████╗ ██╗   ██╗██████╗  ██████╗ ██████╗  █████╗  
██╔══██╗██║   ██║██╔══██╗██╔═══██╗██╔══██╗██╔══██╗ 
███████║██║   ██║██████╔╝██║   ██║██████╔╝███████║ 
██╔══██║██║   ██║██╔══██╗██║   ██║██╔══██╗██╔══██║ 
██║  ██║╚██████╔╝██║  ██║╚██████╔╝██║  ██║██║  ██║ 
╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝ 
                                                   
      ███████╗██╗  ██╗███████╗██╗     ██╗          
      ██╔════╝██║  ██║██╔════╝██║     ██║          
      ███████╗███████║█████╗  ██║     ██║          
      ╚════██║██╔══██║██╔══╝  ██║     ██║          
      ███████║██║  ██║███████╗███████╗███████╗     
      ╚══════╝╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝
"
    else
        content=$(figlet -f slant "$AURORA_HDR_VAL")
    fi

    # Centering Header
    local max_w=0
    while IFS= read -r line; do
        (( ${#line} > max_w )) && max_w=${#line}
    done <<< "$content"
    local pad=$(( (cols - max_w) / 2 ))
    (( pad < 0 )) && pad=0

    while IFS= read -r line; do
        printf "%${pad}s%s\n" "" "$line"
    done <<< "$content" | safe_lolcat

    # --- TELEMETRY ---
    local cpu_load=$(top -l 1 | grep "CPU usage" | awk '{print $3}' | sed 's/%//')
    local disk_free=$(df -h / | tail -1 | awk '{print $4}')
    local batt=$(pmset -g batt | grep -Eo '[0-9]+%' | head -1 || echo "100%")
    
    local stats="⚡ AURORA v$AURORA_VER | 🧠 CPU: ${cpu_load}% | 💾 FREE: $disk_free | 🔋 $batt | 📅 $(date +'%D')"
    local s_pad=$(( (cols - ${#stats}) / 2 ))
    [[ $s_pad -lt 0 ]] && s_pad=0
    printf "%${s_pad}s\033[1;34m%s\033[0m\n" "" "$stats"

    # --- THE SEPARATOR DASH LINE ---
    local line_str=""
    for ((i=1; i<=$cols; i++)); do line_str+="-"; done
    echo "$line_str" | safe_lolcat
}

shell.aurora() {
    case "$1" in
        --display) Show-Aurora ;;
        --sys) sw_vers && sysctl -n machdep.cpu.brand_string ;;
        --update)
            local branch="${2:-main}"
            bash <(curl -s "https://raw.githubusercontent.com/YashB-byte/aurora-shell/$branch/install.sh")
            ;;
        --config) open -a Xcode "$HOME/.aurora-shell_files/aurora-shell_settings" || ${EDITOR:-vi} "$HOME/.aurora-shell_files/aurora-shell_settings" ;;
        --lock) authenticate_user "MANUAL" && Show-Aurora ;;
        --uninstall) rm -rf "$HOME/.aurora-shell_files" && sed -i '' '/aurora-shell_theme/d' ~/.zshrc ;;
        *) echo "Flags: --display, --sys, --update [branch], --config, --lock, --uninstall" ;;
    esac
}
alias aurora="shell.aurora"

# --- SHELL PACKAGE MANAGER ---
PACKAGES_FILE="$HOME/.aurora-shell_files/packages.json"
INSTALLED_DIR="$HOME/.aurora-shell_files/bin"
mkdir -p "$INSTALLED_DIR"
export PATH="$INSTALLED_DIR:$PATH"

if [ ! -f "$PACKAGES_FILE" ]; then
    cat > "$PACKAGES_FILE" << 'PKGEOF'
{
  "packages": {
    "aurora-app": {
      "url": "https://github.com/YashB-byte/Aurora-Shell/releases/latest/download/Aurora-Shell.dmg",
      "type": "dmg",
      "description": "Aurora Shell Terminal App"
    }
  }
}
PKGEOF
fi

shell() {
    case "$1" in
        install)
            local pkg="$2"
            local url=$(jq -r ".packages[\"$pkg\"].url" "$PACKAGES_FILE" 2>/dev/null)
            local type=$(jq -r ".packages[\"$pkg\"].type" "$PACKAGES_FILE" 2>/dev/null)
            
            if [ "$url" = "null" ]; then
                echo "🔍 Not in Aurora registry. Searching Homebrew..."
                if brew info "$pkg" &>/dev/null; then
                    echo "📦 Found in Homebrew: $pkg"
                    echo -n "Install via brew? (y/n): "
                    read confirm
                    [ "$confirm" = "y" ] && brew install "$pkg" && echo "✅ Installed via Homebrew"
                else
                    echo "❌ Package not found in Aurora or Homebrew"
                fi
                return
            fi
            
            echo "📦 Installing $pkg..."
            case "$type" in
                dmg)
                    local tmp="/tmp/$pkg.dmg"
                    curl -L "$url" -o "$tmp"
                    hdiutil attach "$tmp" -quiet
                    local vol=$(ls /Volumes | grep -v Macintosh | head -1)
                    cp -R "/Volumes/$vol"/*.app ~/Applications/ 2>/dev/null
                    hdiutil detach "/Volumes/$vol" -quiet
                    rm "$tmp"
                    echo "✅ Installed to ~/Applications"
                    ;;
                binary)
                    curl -L "$url" -o "$INSTALLED_DIR/$pkg"
                    chmod +x "$INSTALLED_DIR/$pkg"
                    echo "✅ Installed to $INSTALLED_DIR"
                    ;;
                brew)
                    brew install "$pkg"
                    ;;
            esac
            ;;
        search)
            echo "📋 Aurora packages:"
            jq -r '.packages | to_entries[] | "  \(.key) - \(.value.description)"' "$PACKAGES_FILE" 2>/dev/null
            if [ -n "$2" ]; then
                echo ""
                echo "🍺 Homebrew results:"
                brew search "$2" 2>/dev/null | head -10
            fi
            ;;
        list)
            echo "📦 Installed:"
            ls -1 "$INSTALLED_DIR" 2>/dev/null || echo "  (none)"
            ;;
        add)
            echo "📝 Package submission:"
            echo "  Name: $2"
            echo "  URL: $3"
            echo "  Type: ${4:-binary}"
            echo "  Description: ${5:-Custom package}"
            echo ""
            echo -n "Submit for approval? (y/n): "
            read confirm
            if [ "$confirm" = "y" ]; then
                echo "📤 Sending approval request..."
                curl -s -X POST "https://api.github.com/repos/YashB-byte/Aurora-Shell/issues" \
                    -H "Content-Type: application/json" \
                    -d "{\"title\":\"Package Request: $2\",\"body\":\"**Package Name:** $2\n**URL:** $3\n**Type:** ${4:-binary}\n**Description:** ${5:-Custom package}\n\n---\nSubmitted via shell add command\",\"labels\":[\"package-request\"]}" \
                    >/dev/null 2>&1
                
                if [ $? -eq 0 ]; then
                    echo "✅ Request submitted. You'll be notified when approved."
                    echo "   Track at: https://github.com/YashB-byte/Aurora-Shell/issues"
                else
                    echo "⚠️  Could not submit request. Add manually to local registry? (y/n): "
                    read local_add
                    if [ "$local_add" = "y" ]; then
                        local tmp=$(mktemp)
                        jq ".packages[\"$2\"] = {\"url\": \"$3\", \"type\": \"${4:-binary}\", \"description\": \"${5:-Custom}\"}" "$PACKAGES_FILE" > "$tmp" 2>/dev/null
                        mv "$tmp" "$PACKAGES_FILE"
                        echo "✅ Added $2 locally (not in official registry)"
                    fi
                fi
            fi
            ;;
        remove)
            rm -f "$INSTALLED_DIR/$2"
            echo "✅ Removed $2"
            ;;
        *)
            echo "Usage: shell install|search|list|add|remove"
            ;;
    esac
}

rainbow_prompt() {
  local raw_text="${AURORA_ID} %n@%m %* > "
  local expanded_text=$(print -P "$raw_text")
  local colors=(196 202 226 190 82 46 48 51 45 39 27 21 57 93 129 165 201 199)
  local out=""
  for (( j=1; j<=${#expanded_text}; j++ )); do
    out+="%{%F{${colors[$(( (j % ${#colors}) + 1 ))]}}%}${expanded_text[j]}%{%f%}"
  done
  echo -n "$out"
}

authenticate_user
Show-Aurora
EOF
}

# --- EXECUTE ---
sync_env
dev_tools_bootstrap
run_wizard
generate_theme

sed -i '' '/aurora-shell_theme/d' ~/.zshrc 2>/dev/null
echo "source $THEME_FILE" >> "$HOME/.zshrc"

echo "🌀 Checking Aurora-shell..."

cd "$HOME"
# Search the entire home folder for a REAL Aurora-shell Git repo
FOUND_REPO=$(cd ~
find "$HOME" -maxdepth 10 -type d -name "aurora-shell" 2>/dev/null | while read -r dir; do
    if [ -d "$dir/.git" ]; then
        ORIGIN=$(git -C "$dir" remote get-url origin 2>/dev/null)
        if [ "$ORIGIN" = "$GIT_CLONE" ]; then
            echo "$dir"
            break
        fi
    fi
done)

if [ -n "$FOUND_REPO" ]; then
    echo "🔄 Found existing Aurora-shell repo at: $FOUND_REPO"
    cd "$FOUND_REPO"
    git pull --rebase --autostash || true
else
    echo "⬇ No matching repo found — cloning fresh copy..."
    cd "$DATA_DIR"
    git clone "$GIT_CLONE" aurora-shell || true
fi

echo -e "\n\033[1;32m✅ v5.4.0 Deployed. 🛠️Xcode installed.\033[0m"

echo "welcome to Aurora-Shell" | safe_lolcat
