#!/bin/bash
# --- AURORA-SHELL MASTER v5.8.8 ---
# VERSION: 5.8.8
# FIX: Sentinel Auth Visuals + Separator + CPU/Disk Telemetry

# --- PATH CONFIGURATION ---
DATA_DIR="$HOME/.aurora-shell_files"
THEME_FILE="$DATA_DIR/aurora-shell_theme"
CONFIG_FILE="$DATA_DIR/aurora-shell_settings"
REPO_BASE="https://raw.githubusercontent.com/YashB-byte/aurora-shell"
GIT_CLONE="https://github.com/YashB-byte/aurora-shell.git"

mkdir -p "$DATA_DIR"
[ -f "$THEME_FILE" ] && rm "$THEME_FILE"
echo "aurora-shell installer" | lolcat

# --- SYNC ENVIRONMENT ---
sync_env() {
    echo -ne "\033[1;33m🛠️  Syncing Environment... \033[0m"
    if ! command -v brew >/dev/null 2>&1; then
        mkdir -p "$HOME/.brew"
        curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C "$HOME/.brew"
        export PATH="$HOME/.brew/bin:$PATH"
    fi
    brew install figlet lolcat pygments 2>/dev/null
    echo -e "\033[1;32mREADY\033[0m"
}

# --- DEV TOOLS BOOTSTRAP (BASH 3.2 SAFE) ---
dev_tools_bootstrap() {
    echo -e "\n\033[1;36m--- DEV TOOLS SETUP (HYBRID MODE) ---\033[0m"

    tools=(
        "Git:git"
        "GitHub_CLI:gh"
        "NodeJS:node"
        "Python3:python@3.14"
        "Java:openjdk"
        "Go:go"
        "Rust:rust"
        "Docker:docker-desktop"
        "AWS_CLI:awscli"
        "Azure_CLI:azure-cli"
    )

    for entry in "${tools[@]}"; do
        name="${entry%%:*}"
        formula="${entry##*:}"

        printf "Install %s? (y/n): " "$name"
        read ans
        if [ "$ans" = "y" ]; then
            case "$name" in
                "Docker")
                    if command -v sudo >/dev/null 2>&1; then
                        brew install --cask docker-desktop
                    else
                        echo "Skipping Docker: sudo not available for this user."
                    fi
                    ;;
                *)
                    brew install "$formula"
                    ;;
            esac
        fi
    done
}

# --- CONFIG WIZARD ---
run_wizard() {
    echo -e "\n\033[1;32m--- AURORA CONFIGURATION WIZARD ---\033[0m"
    [ -f "$CONFIG_FILE" ] && source "$CONFIG_FILE"
    
    read -s -p "🔐 Set Terminal PIN (Enter for none): " NEW_PW < /dev/tty; echo ""
    echo "🎨 1) Mega-Block 2) Custom Slant"
    read -p "Selection: " choice < /dev/tty
    if [ "$choice" == "2" ]; then 
        HDR_MODE="CUSTOM"; read -p "✍️ Header Name: " HDR_VAL < /dev/tty
    else 
        HDR_MODE="BLOCK"; HDR_VAL="Aurora-Shell"
    fi

    printf "🎂 Birthday (MMDD): "
    read BDAY
    printf "🆔 Prompt ID: "
    read P_ID

    cat << EOF > "$CONFIG_FILE"
AURORA_VER="5.8.8"
AURORA_PW="${NEW_PW:-$AURORA_PW}"
AURORA_HDR_MODE="$HDR_MODE"
AURORA_HDR_VAL="$HDR_VAL"
AURORA_USER_BDAY="${BDAY:-$AURORA_USER_BDAY}"
AURORA_ID="${P_ID:-$AURORA_ID}"
EOF
}

# --- THEME ENGINE ---
generate_theme() {
cat << 'EOF' > "$THEME_FILE"
#!/bin/zsh
# Generated by Aurora-Shell Installer
source "$HOME/.aurora-shell_files/aurora-shell_settings"

# -- XCODE INSTALLER (macOS) --
install_xcode_if_needed() {
    # Only attempt on macOS
    if [[ "$(uname)" != "Darwin" ]]; then
        return
    fi

    # If Xcode.app exists, do nothing
    if [ -d "/Applications/Xcode.app" ] || [ -d "$HOME/Applications/Xcode.app" ]; then
        echo "✔ Xcode found."
        return
    fi

    echo "⚠ Xcode not found — attempting installation..."

    # Ensure Homebrew exists
    if ! command -v brew &> /dev/null; then
        echo "⚠ Homebrew missing — installing Homebrew..."
        mkdir -p "$HOME/.brew"
        curl -L https://github.com/Homebrew/brew/tarball/master \
            | tar xz --strip 1 -C "$HOME/.brew"
        export PATH="$HOME/.brew/bin:$PATH"
    fi

    # Try installing full Xcode via cask (requires App Store download)
    if brew info --cask xcode >/dev/null 2>&1; then
        echo "⬇ Installing Xcode via Homebrew Cask (this may open the App Store)..."
        brew install --cask xcode || true
    fi

    # Fallback: ensure Command Line Tools are installed
    if ! xcode-select -p >/dev/null 2>&1; then
        echo "⬇ Installing Xcode Command Line Tools..."
        xcode-select --install || true
    fi
}

install_xcode_if_needed

# -- HELPER: SAFE LOLCAT --
safe_lolcat() {
    if command -v lolcat &> /dev/null; then command lolcat; else cat; fi
}

authenticate_user() {
    local target_pw="${1:-$AURORA_PW}"
    [[ -z "$target_pw" ]] && return
    clear
    echo "           .---.
          /     \\
         | (00)  |  SYSTEM ENCRYPTED
          \\  ^  /
           '---'
     ╔════════════════════════════════════════╗
     ║     AURORA-SHELL SECURITY TERMINAL     ║
     ╚════════════════════════════════════════╝" | safe_lolcat
    while true; do
        echo -ne "[AUTH] Key: "
        if ! read -s in_pw; then
            echo ""
            echo "DENIED"
            continue
        fi
        echo ""

        if [[ "$in_pw" == "$target_pw" ]]; then
            if [[ ! -o interactive ]]; then
                trap INT
                trap TSTP
                trap QUIT
            fi
            clear
            break
        else
            echo "DENIED"
        fi
    done
}

Show-Aurora() {
    source "$HOME/.aurora-shell_files/aurora-shell_settings"
    local cols=$(tput cols)
    local content=""

    if [[ "$AURORA_HDR_MODE" == "BLOCK" ]]; then
        content="
 █████╗ ██╗   ██╗██████╗  ██████╗ ██████╗  █████╗  
██╔══██╗██║   ██║██╔══██╗██╔═══██╗██╔══██╗██╔══██╗ 
███████║██║   ██║██████╔╝██║   ██║██████╔╝███████║ 
██╔══██║██║   ██║██╔══██╗██║   ██║██╔══██╗██╔══██║ 
██║  ██║╚██████╔╝██║  ██║╚██████╔╝██║  ██║██║  ██║ 
╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝ 
                                                   
      ███████╗██╗  ██╗███████╗██╗     ██╗          
      ██╔════╝██║  ██║██╔════╝██║     ██║          
      ███████╗███████║█████╗  ██║     ██║          
      ╚════██║██╔══██║██╔══╝  ██║     ██║          
      ███████║██║  ██║███████╗███████╗███████╗     
      ╚══════╝╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝
"
    else
        content=$(figlet -f slant "$AURORA_HDR_VAL")
    fi

    # Centering Header
    local max_w=0
    while IFS= read -r line; do
        (( ${#line} > max_w )) && max_w=${#line}
    done <<< "$content"
    local pad=$(( (cols - max_w) / 2 ))
    (( pad < 0 )) && pad=0

    while IFS= read -r line; do
        printf "%${pad}s%s\n" "" "$line"
    done <<< "$content" | safe_lolcat

    # --- TELEMETRY ---
    local cpu_load=$(top -l 1 | grep "CPU usage" | awk '{print $3}' | sed 's/%//')
    local disk_free=$(df -h / | tail -1 | awk '{print $4}')
    local batt=$(pmset -g batt | grep -Eo '[0-9]+%' | head -1 || echo "100%")
    
    local stats="⚡ AURORA v$AURORA_VER | 🧠 CPU: ${cpu_load}% | 💾 FREE: $disk_free | 🔋 $batt | 📅 $(date +'%D')"
    local s_pad=$(( (cols - ${#stats}) / 2 ))
    [[ $s_pad -lt 0 ]] && s_pad=0
    printf "%${s_pad}s\033[1;34m%s\033[0m\n" "" "$stats"

    # --- THE SEPARATOR DASH LINE ---
    local line_str=""
    for ((i=1; i<=$cols; i++)); do line_str+="-"; done
    echo "$line_str" | safe_lolcat
}

shell.aurora() {
    case "$1" in
        --display) Show-Aurora ;;
        --sys) sw_vers && sysctl -n machdep.cpu.brand_string ;;
        --update)
            local branch="${2:-main}"
            bash <(curl -s "https://raw.githubusercontent.com/YashB-byte/aurora-shell/$branch/install.sh")
            ;;
        --config) open -a Xcode "$HOME/.aurora-shell_files/aurora-shell_settings" || ${EDITOR:-vi} "$HOME/.aurora-shell_files/aurora-shell_settings" ;;
        --lock) authenticate_user "MANUAL" && Show-Aurora ;;
        --uninstall) rm -rf "$HOME/.aurora-shell_files" && sed -i '' '/aurora-shell_theme/d' ~/.zshrc ;;
        *) echo "Flags: --display, --sys, --update [branch], --config, --lock, --uninstall" ;;
    esac
}
alias aurora="shell.aurora"

rainbow_prompt() {
  local raw_text="${AURORA_ID} %n@%m %* > "
  local expanded_text=$(print -P "$raw_text")
  local colors=(196 202 226 190 82 46 48 51 45 39 27 21 57 93 129 165 201 199)
  local out=""
  for (( j=1; j<=${#expanded_text}; j++ )); do
    out+="%{%F{${colors[$(( (j % ${#colors}) + 1 ))]}}%}${expanded_text[j]}%{%f%}"
  done
  echo -n "$out"
}

authenticate_user
Show-Aurora
EOF
}

# --- EXECUTE ---
sync_env
dev_tools_bootstrap
run_wizard
generate_theme

sed -i '' '/aurora-shell_theme/d' ~/.zshrc 2>/dev/null
echo "source $THEME_FILE" >> "$HOME/.zshrc"

echo "Checking Aurora-shell..."

TARGET_REPO="https://github.com/YashB-byte/aurora-shell.git"

# Search for a real Git repo named aurora-shell that belongs to YOU
FOUND_REPO=$(find "$HOME" -type d -name "aurora-shell" -maxdepth 5 2>/dev/null | while read -r dir; do
    if [ -d "$dir/.git" ]; then
        ORIGIN=$(git -C "$dir" remote get-url origin 2>/dev/null)
        if [ "$ORIGIN" = "$TARGET_REPO" ]; then
            echo "$dir"
            break
        fi
    fi
done)

if [ -n "$FOUND_REPO" ]; then
    echo "🔄 Found your Aurora-shell repo at: $FOUND_REPO"
    cd "$FOUND_REPO"
    git pull --rebase --autostash || true
else
    echo "⬇ No matching repo found — cloning fresh copy..."
    mkdir -p "$DATA_DIR"
    cd "$DATA_DIR"
    git clone "$TARGET_REPO" aurora-shell || true
fi

cd "$HOME"

echo -e "\n\033[1;32m✅ v5.8.7 Deployed. Xcode installed.\033[0m"
