#!/bin/bash
# --- AURORA-SHELL MASTER v5.8.7 ---
# VERSION: 5.8.7
# FIX: Sentinel Auth Visuals + Separator + CPU/Disk Telemetry

# --- PATH CONFIGURATION ---
DATA_DIR="$HOME/.aurora-shell_files"
THEME_FILE="$DATA_DIR/aurora-shell_theme"
CONFIG_FILE="$DATA_DIR/aurora-shell_settings"
REPO_BASE="https://raw.githubusercontent.com/YashB-byte/aurora-shell"

mkdir -p "$DATA_DIR"
[ -f "$THEME_FILE" ] && rm "$THEME_FILE"

# --- SYNC ENVIRONMENT ---
sync_env() {
    echo -ne "\033[1;33m🛠️  Syncing Environment... \033[0m"
    if ! command -v brew &> /dev/null; then
        mkdir -p "$HOME/.brew" && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C "$HOME/.brew"
        export PATH="$HOME/.brew/bin:$PATH"
    fi
    brew install figlet lolcat pygments 2>/dev/null
    echo -e "\033[1;32mREADY\033[0m"
}

# --- THE WIZARD ---
run_wizard() {
    echo -e "\n\033[1;32m--- AURORA CONFIGURATION WIZARD ---\033[0m"
    [ -f "$CONFIG_FILE" ] && source "$CONFIG_FILE"
    
    read -s -p "🔐 Set Terminal PIN (Enter for none): " NEW_PW < /dev/tty; echo ""
    echo "🎨 1) Mega-Block 2) Custom Slant"
    read -p "Selection: " choice < /dev/tty
    if [ "$choice" == "2" ]; then 
        HDR_MODE="CUSTOM"; read -p "✍️ Header Name: " HDR_VAL < /dev/tty
    else 
        HDR_MODE="BLOCK"; HDR_VAL="Aurora-Shell"
    fi
    read -p "🎂 Birthday (MMDD): " BDAY < /dev/tty
    read -p "🆔 Prompt ID: " P_ID < /dev/tty

    cat << EOF > "$CONFIG_FILE"
AURORA_VER="5.8.7"
AURORA_PW="${NEW_PW:-$AURORA_PW}"
AURORA_HDR_MODE="$HDR_MODE"
AURORA_HDR_VAL="$HDR_VAL"
AURORA_USER_BDAY="${BDAY:-$AURORA_USER_BDAY}"
AURORA_ID="${P_ID:-$AURORA_ID}"
EOF
}

# --- THEME ENGINE ---
generate_theme() {
    cat << 'EOF' > "$THEME_FILE"
#!/bin/zsh
# Generated by Aurora-Shell Installer
source "$HOME/.aurora-shell_files/aurora-shell_settings"

# -- VS CODE ALIAS + AUTO-INSTALL ENGINE (SUDO-AWARE) --
find_or_install_vscode() {

    # Detect sudo capability (Option B)
    if sudo -n true 2>/dev/null; then
        SUDO_AVAILABLE=true
    else
        SUDO_AVAILABLE=false
    fi

    local locs=(
        "/Applications/Visual Studio Code.app"
        "$HOME/Applications/Visual Studio Code.app"
        "/Applications/Visual Studio Code - Insiders.app"
        "$HOME/Applications/Visual Studio Code - Insiders.app"
    )

    # Search for existing VS Code installations
    for loc in "${locs[@]}"; do
        if [ -d "$loc" ]; then
            alias code="$loc/Contents/Resources/app/bin/code"
            echo "✔ VS Code found at: $loc"
            return
        fi
    done

    echo "⚠ VS Code not found — installing..."

    # Ensure Homebrew exists
    if ! command -v brew &> /dev/null; then
        echo "⚠ Homebrew missing — installing Homebrew..."
        mkdir -p "$HOME/.brew"
        curl -L https://github.com/Homebrew/brew/tarball/master \
            | tar xz --strip 1 -C "$HOME/.brew"
        export PATH="$HOME/.brew/bin:$PATH"
    fi

    # Install path logic
    if [ "$SUDO_AVAILABLE" = true ]; then
        echo "🔐 Sudo available — installing VS Code into /Applications"
        brew install --cask visual-studio-code --appdir="/Applications"
        INSTALL_PATH="/Applications/Visual Studio Code.app"
    else
        echo "🚫 No sudo — installing VS Code into ~/Applications"
        mkdir -p "$HOME/Applications"
        brew install --cask visual-studio-code --appdir="$HOME/Applications"
        INSTALL_PATH="$HOME/Applications/Visual Studio Code.app"
    fi

    # Re-check after install
    if [ -d "$INSTALL_PATH" ]; then
        alias code="$INSTALL_PATH/Contents/Resources/app/bin/code"
        echo "✔ VS Code installed and alias created."
    else
        echo "❌ VS Code installation failed or installed somewhere unexpected."
    fi
}

find_or_install_vscode

# -- HELPER: SAFE LOLCAT --
safe_lolcat() {
    if command -v lolcat &> /dev/null; then command lolcat; else cat; fi
}

authenticate_user() {
    local target_pw="${1:-$AURORA_PW}"
    [[ -z "$target_pw" ]] && return
    clear
    echo "           .---.
          /     \\
         | (00)  |  SYSTEM ENCRYPTED
          \\  ^  /
           '---'
     ╔════════════════════════════════════════╗
     ║     AURORA-SHELL SECURITY TERMINAL     ║
     ╚════════════════════════════════════════╝" | safe_lolcat
    while true; do
        echo -ne "\033[1;36m[AUTH] Key: \033[0m"; read -s in_pw; echo ""
        [[ "$in_pw" == "$target_pw" ]] && { clear; break; } || echo -e "\033[1;41m DENIED \033[0m"
    done
}

Show-Aurora() {
    source "$HOME/.aurora-shell_files/aurora-shell_settings"
    local cols=$(tput cols)
    local content=""

    if [ "$AURORA_HDR_MODE" = "BLOCK" ]; then
        content="
 █████╗ ██╗   ██╗██████╗  ██████╗ ██████╗  █████╗  
██╔══██╗██║   ██║██╔══██╗██╔═══██╗██╔══██╗██╔══██╗ 
███████║██║   ██║██████╔╝██║   ██║██████╔╝███████║ 
██╔══██║██║   ██║██╔══██╗██║   ██║██╔══██╗██╔══██║ 
██║  ██║╚██████╔╝██║  ██║╚██████╔╝██║  ██║██║  ██║ 
╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝ 
                                                   
      ███████╗██╗  ██╗███████╗██╗     ██╗          
      ██╔════╝██║  ██║██╔════╝██║     ██║          
      ███████╗███████║█████╗  ██║     ██║          
      ╚════██║██╔══██║██╔══╝  ██║     ██║          
      ███████║██║  ██║███████╗███████╗███████╗     
      ╚══════╝╚═╝  ╚═╝╚══════╝╚══════╝╚══════╝"
    else
        content=$(figlet -f slant "$AURORA_HDR_VAL")
    fi

    # Centering Header
    local max_w=0
    while IFS= read -r line; do
        (( ${#line} > max_w )) && max_w=${#line}
    done <<< "$content"
    local pad=$(( (cols - max_w) / 2 ))
    [[ $pad -lt 0 ]] && pad=0

    while IFS= read -r line; do
        printf "%${pad}s%s\n" "" "$line"
    done <<< "$content" | safe_lolcat

    # --- TELEMETRY ---
    local cpu_load=$(top -l 1 | grep "CPU usage" | awk '{print $3}' | sed 's/%//')
    local disk_free=$(df -h / | tail -1 | awk '{print $4}')
    local batt=$(pmset -g batt | grep -Eo '[0-9]+%' | head -1 || echo "100%")
    
    local stats="⚡ AURORA v$AURORA_VER | 🧠 CPU: ${cpu_load}% | 💾 FREE: $disk_free | 🔋 $batt | 📅 $(date +'%D')"
    local s_pad=$(( (cols - ${#stats}) / 2 ))
    [[ $s_pad -lt 0 ]] && s_pad=0
    printf "%${s_pad}s\033[1;34m%s\033[0m\n" "" "$stats"

    # --- THE SEPARATOR DASH LINE ---
    local line_str=""
    for ((i=1; i<=$cols; i++)); do line_str+="-"; done
    echo "$line_str" | safe_lolcat
}

shell.aurora() {
    case "$1" in
        --display) Show-Aurora ;;
        --sys) sw_vers && sysctl -n machdep.cpu.brand_string ;;
        --update)
            local branch="${2:-main}"
            bash <(curl -s "https://raw.githubusercontent.com/YashB-byte/aurora-shell/$branch/install.sh")
            ;;
        --config) code "$HOME/.aurora-shell_files/aurora-shell_settings" ;;
        --lock) authenticate_user "MANUAL" && Show-Aurora ;;
        --uninstall) rm -rf "$HOME/.aurora-shell_files" && sed -i '' '/aurora-shell_theme/d' ~/.zshrc ;;
        *) echo "Flags: --display, --sys, --update [branch], --config, --lock, --uninstall" ;;
    esac
}
alias aurora="shell.aurora"

rainbow_prompt() {
  local raw_text="${AURORA_ID} %n@%m %* > "
  local expanded_text=$(print -P "$raw_text")
  local colors=(196 202 226 190 82 46 48 51 45 39 27 21 57 93 129 165 201 199)
  local out=""
  for (( j=1; j<=${#expanded_text}; j++ )); do
    out+="%{%F{${colors[$(( (j % ${#colors}) + 1 ))]}}%}${expanded_text[j]}%{%f%}"
  done
  echo -n "$out"
}

authenticate_user
setopt PROMPT_SUBST
PROMPT='$(rainbow_prompt)'
Show-Aurora
EOF
}

# --- EXECUTE ---
sync_env
run_wizard
generate_theme

sed -i '' '/aurora-shell_theme/d' ~/.zshrc 2>/dev/null
echo "source $THEME_FILE" >> "$HOME/.zshrc"

echo -e "\n\033[1;32m✅ v5.8.7 Deployed. Security Terminal Visuals Updated.\033[0m"
